# agentmanager
agentmanager:
  port:
    web: 8006
  contextPath: /agent-manager

# 日志相关配置
logging:
  pattern:
    file: "[%level][%d{yyyy-MM-dd'T'HH:mm:ss.SSS}][%t] %msg%xEx%n"
  path: .
  file:
    max-history: 7
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug

# mybatis公共配置
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:mybatis/*.xml

spring:
  datasource:
    name: data
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:8099/agent_manager_v2?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&allowMultiQueries=true&useSSL=false
      username:
      password:
      initialSize: 10
      validationQueryTimeout: 5000
      transactionQueryTimeout: 60000
      minIdle: 10
      maxActive: 30
      max-wait: 60000
      keepAlive: true
      time-between-eviction-runs-millis: 1000
      min-evictable-idle-time-millis: 300000
      defaultAutoCommit: true
      validationQuery: select 'x'
      testWhileIdle: true
      testOnReturn: false
      testOnBorrow: true
      logAbandoned: true
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      filters: stat,wall
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  messages:
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 600MB
      max-request-size: 600MB
  auv-job:
    jdbc-url: jdbc:mysql://localhost:8099/agent_manager_v2?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&allowMultiQueries=true&useSSL=false
    username:
    password:
    driver-class-name: com.mysql.jdbc.Driver
    max-lifetime: 60000
    init-sql: true
    init-thread-num: 10
    max-thread-num: 20

# 事务超时时间
spring.transaction.default-timeout: 300

kcm:
  enabled: true
  gift:
    endpoint: 'url'
    accessKeyID: 'id'
    secretAccessKey: 'secret'
    bucket: agentmanager

lam:
  n9e-job:
    base-url:
    timeout: 300
    account:
    script-file: lam_script.sh
    user-token:

metadata:
  sync:
    request:
      service:
        url:
        enabled: false
      host:
        url:
      kafkacluster:
        url:
        enabled: false
      containers:
        url:
      permission:
        url:
        srv-token:
        user-token:
        enabled:
agent:
  metrics:
    datasource:
      elasticsearch:
        ip:
        port:
        appId:
        appSecret:
        agentMetricsIndexName:
        agentErrorLogIndexName:
  http:
    path:
      request:
        url: http://%s:%d/swan-agent/path
        port: 2023
        body:

k8s:
  service-key: servicename
  path-name: logpath
